//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPathTeam.Dates.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPathTeam.Dates.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authentication.
        /// </summary>
        internal static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The business day of the month..
        /// </summary>
        internal static string BDotMDescription {
            get {
                return ResourceManager.GetString("BDotMDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Business day of the Month.
        /// </summary>
        internal static string BDotMDisplayName {
            get {
                return ResourceManager.GetString("BDotMDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date 1 as Datetime.
        /// </summary>
        internal static string Date1DTDescription {
            get {
                return ResourceManager.GetString("Date1DTDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date 1 (DateTime).
        /// </summary>
        internal static string Date1DTDisplayName {
            get {
                return ResourceManager.GetString("Date1DTDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date 1 as a string.
        /// </summary>
        internal static string Date1StringDescription {
            get {
                return ResourceManager.GetString("Date1StringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date 1 (String).
        /// </summary>
        internal static string Date1StringDisplayName {
            get {
                return ResourceManager.GetString("Date1StringDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date 2 as Datetime.
        /// </summary>
        internal static string Date2DTDescription {
            get {
                return ResourceManager.GetString("Date2DTDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date 2 (DateTime).
        /// </summary>
        internal static string Date2DTDisplayName {
            get {
                return ResourceManager.GetString("Date2DTDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date 2 as string.
        /// </summary>
        internal static string Date2StringDescription {
            get {
                return ResourceManager.GetString("Date2StringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date 2 (String).
        /// </summary>
        internal static string Date2StringDisplayName {
            get {
                return ResourceManager.GetString("Date2StringDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The date in DateTime format..
        /// </summary>
        internal static string DateDescription {
            get {
                return ResourceManager.GetString("DateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date (DateTime).
        /// </summary>
        internal static string DateDisplayName {
            get {
                return ResourceManager.GetString("DateDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date format..
        /// </summary>
        internal static string DateFormatDescription {
            get {
                return ResourceManager.GetString("DateFormatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date format.
        /// </summary>
        internal static string DateFormatDisplayName {
            get {
                return ResourceManager.GetString("DateFormatDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The date in String format..
        /// </summary>
        internal static string DateStringDescription {
            get {
                return ResourceManager.GetString("DateStringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date (String).
        /// </summary>
        internal static string DateStringDisplayName {
            get {
                return ResourceManager.GetString("DateStringDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Day of the date. Expected value between 1 and 31..
        /// </summary>
        internal static string DayDescription {
            get {
                return ResourceManager.GetString("DayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Day.
        /// </summary>
        internal static string DayDisplayName {
            get {
                return ResourceManager.GetString("DayDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hours. Expected value between 00 and 23..
        /// </summary>
        internal static string HoursDescription {
            get {
                return ResourceManager.GetString("HoursDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hours.
        /// </summary>
        internal static string HoursDisplayName {
            get {
                return ResourceManager.GetString("HoursDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Input as Datetime.
        /// </summary>
        internal static string InputDatetime {
            get {
                return ResourceManager.GetString("InputDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Input as String.
        /// </summary>
        internal static string InputString {
            get {
                return ResourceManager.GetString("InputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The result of the Is Leap function check..
        /// </summary>
        internal static string IsLeapDescription {
            get {
                return ResourceManager.GetString("IsLeapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Is Leap.
        /// </summary>
        internal static string IsLeapDisplayName {
            get {
                return ResourceManager.GetString("IsLeapDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please provide a value for {0}.
        /// </summary>
        internal static string MetadataValidationError {
            get {
                return ResourceManager.GetString("MetadataValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minutes. Expected value between 00 and 59..
        /// </summary>
        internal static string MinutesDescription {
            get {
                return ResourceManager.GetString("MinutesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minutes.
        /// </summary>
        internal static string MinutesDisplayName {
            get {
                return ResourceManager.GetString("MinutesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Month of the date. Expected value between 1 and 12..
        /// </summary>
        internal static string MonthDescription {
            get {
                return ResourceManager.GetString("MonthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Month.
        /// </summary>
        internal static string MonthDisplayName {
            get {
                return ResourceManager.GetString("MonthDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The position of the day (could be First or Last).
        /// </summary>
        internal static string PositionDescription {
            get {
                return ResourceManager.GetString("PositionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Position.
        /// </summary>
        internal static string PositionDisplayName {
            get {
                return ResourceManager.GetString("PositionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seconds. Expected value between 00 and 59..
        /// </summary>
        internal static string SecondsDescription {
            get {
                return ResourceManager.GetString("SecondsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seconds.
        /// </summary>
        internal static string SecondsDisplayName {
            get {
                return ResourceManager.GetString("SecondsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The number of the week returned..
        /// </summary>
        internal static string WeekNbDescription {
            get {
                return ResourceManager.GetString("WeekNbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Week Number.
        /// </summary>
        internal static string WeekNbDisplayName {
            get {
                return ResourceManager.GetString("WeekNbDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Year to be tesed.
        /// </summary>
        internal static string YearDescription {
            get {
                return ResourceManager.GetString("YearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Year.
        /// </summary>
        internal static string YearDisplayName {
            get {
                return ResourceManager.GetString("YearDisplayName", resourceCulture);
            }
        }
    }
}
